{
  "hash": "a8814d5ed7ab4e9d9f06a02cd08661b3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Pipeline Observation: Ferry & Ellis Transformation Report\"\nsubtitle: \"EDA 2 — CCHS Data Pipeline: 1-ferry.R and 2-ellis.R\"\nauthor: \"Andriy Koval\"\ndate: \"2026-03-05\"\nformat:\n  html:\n    page-layout: full\n    toc: true\n    toc-location: right\n    code-fold: show\n    theme: yeti\n    highlight-style: breeze\n    code-line-numbers: true\n    self-contained: true\n    embed-resources: true\n    keep-md: false\neditor: visual\neditor_options:\n  chunk_output_type: console\n---\n\n# Mission\n\nThis document **observes and documents** the two data manipulation scripts that build the CCHS analytical dataset used in the study *\"Predictors of Work Absenteeism Associated with Chronic Conditions Among Canadian Workers\"*. It does not perform statistical analysis — it tracks what each script does, how many rows and variables are affected at each step, and ties every operation back to the requirements in `stats_instructions_v3.md`.\n\n**Data genealogy:**\n\n```         \nCCHS2010_LOP.sav  ──┐\n                     ├──► 1-ferry.R ──► cchs-1.sqlite ──► 2-ellis.R ──► cchs_analytical.parquet\nCCHS_2014_EN_PUMF.sav ──┘                                              └──► sample_flow.parquet\n```\n\nThis report is split into two parts:\n\n-   **Part A — Ferry Observation**: What `1-ferry.R` receives, what it does, and what it produces\n-   **Part B — Ellis Observation**: What `2-ellis.R` receives, all transformations applied, and what the final analytical dataset contains — including the effect of different configuration flag scenarios\n\n# Environment\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Packages used in this report\"}\nlibrary(magrittr)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(ggplot2)\nlibrary(forcats)\nlibrary(stringr)\nlibrary(scales)\nlibrary(janitor)\nlibrary(fs)\nrequireNamespace(\"DBI\")\nrequireNamespace(\"RSQLite\")\nrequireNamespace(\"arrow\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Project-level functions\"}\nbase::source(\"./scripts/common-functions.R\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Path constants and white-list counts\"}\nlocal_root  <- \"./analysis/eda-2/\"\nprints_folder <- paste0(local_root, \"prints/\")\nif (!fs::dir_exists(prints_folder)) fs::dir_create(prints_folder)\n\n# Input paths (ferry and ellis outputs)\npath_cchs1_sqlite    <- \"./data-private/derived/cchs-1.sqlite\"\npath_cchs2_sqlite    <- \"./data-private/derived/cchs-2.sqlite\"\npath_cchs2_parquet   <- \"./data-private/derived/cchs-2-tables\"\npath_analytical_pq   <- file.path(path_cchs2_parquet, \"cchs_analytical.parquet\")\npath_sampleflow_pq   <- file.path(path_cchs2_parquet, \"sample_flow.parquet\")\n\n# White-list variable counts (from 2-ellis.R globals — for documentation charts)\nn_confirmed          <- 13L   # vars_confirmed\nn_inferred_ccc       <- 19L   # vars_inferred_ccc\nn_inferred_other     <- 37L   # predisposing (12) + facilitating (12) + needs (5) + id (1) + ~7 misc\n# bootstrap weights are pattern-selected (~500), not in white-list count\n# CCHS 2010 SPSS file has ~600+ columns; CCHS 2014 similar size\n# (update these when actual ferry output is available)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Helper functions (with_data, etc.)\"}\n# Helper: safely run a block only if a file exists; print a notice otherwise\nwith_data <- function(path, expr, label = path) {\n  if (file.exists(path)) {\n    force(expr)\n  } else {\n    message(\"⚠ Data not available — skipping: \", label)\n    invisible(NULL)\n  }\n}\n\n# ==============================================================================\n# SECTION A: FERRY OBSERVATION  (1-ferry.R)\n# ==============================================================================\n```\n:::\n\n\n------------------------------------------------------------------------\n\n# Part A — Ferry Observation (`1-ferry.R`) {#part-a}\n\n## What is the Ferry Pattern?\n\nThe **Ferry Pattern** transports raw data from its source format into a local staging store with **zero semantic transformation**. The ferry script is intentionally limited: it is forbidden from renaming columns (beyond `clean_names()` sanitization), selecting subsets, recoding values, or excluding rows. Every such decision is deferred to the Ellis script.\n\n::: {.callout-note icon=\"false\"}\n**Requirement — §2.1 Database** (`stats_instructions_v3.md`):\n\n> The analysis uses two cycles of the Canadian Community Health Survey (CCHS), a publicly available, anonymized, nationally representative survey conducted by Statistics Canada:\n>\n> -   **CCHS 2010-2011** (Annual Component)\n> -   **CCHS 2013-2014** (Annual Component)\n>\n> The relevant modules required are: **Chronic Conditions module (CCC)**, **Loss of Productivity module (LOP)**, and **demographic and socioeconomic variables** from the main questionnaire.\n:::\n\n## A.1 Inputs\n\n| File                    | Description                          | Format      |\n|------------------------|------------------------|------------------------|\n| `CCHS2010_LOP.sav`      | CCHS 2010-2011 Annual Component PUMF | SPSS (.sav) |\n| `CCHS_2014_EN_PUMF.sav` | CCHS 2013-2014 Annual Component PUMF | SPSS (.sav) |\n\nBoth files reside in `data-private/raw/2026-02-19/` and are not version-controlled (private microdata).\n\n## A.2 Operations\n\nThree lightweight technical operations are applied to each file — no data values are changed:\n\n| Step | Function | What it does |\n|------------------------|------------------------|------------------------|\n| 1 | `haven::read_sav()` | Reads SPSS binary into an R data frame, preserving all columns and numeric codes |\n| 2 | `haven::zap_labels()` + `haven::zap_label()` | Strips SPSS value labels and variable labels — SQLite cannot store them; numeric codes are retained |\n| 3 | `janitor::clean_names()` | Lowercases all column names and replaces spaces/special characters with underscores (e.g., `LOPG040` → `lopg040`) |\n\nNo rows are removed. No values are changed. No columns are added or dropped.\n\n## A.3 Output Size\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Load ferry metadata from cchs-1.sqlite\"}\n# Connect to cchs-1.sqlite and pull basic metadata from both cycle tables\n\nferry_meta <- NULL   # filled below when data available\n\nif (file.exists(path_cchs1_sqlite)) {\n  cnn <- DBI::dbConnect(RSQLite::SQLite(), path_cchs1_sqlite)\n\n  tables_in_db <- DBI::dbListTables(cnn)\n\n  n_rows_2010 <- DBI::dbGetQuery(cnn, \"SELECT COUNT(*) AS n FROM cchs_2010_raw\")$n\n  n_cols_2010 <- ncol(DBI::dbGetQuery(cnn, \"SELECT * FROM cchs_2010_raw LIMIT 1\"))\n\n  n_rows_2014 <- DBI::dbGetQuery(cnn, \"SELECT COUNT(*) AS n FROM cchs_2014_raw\")$n\n  n_cols_2014 <- ncol(DBI::dbGetQuery(cnn, \"SELECT * FROM cchs_2014_raw LIMIT 1\"))\n\n  # Column names from both cycles\n  cols_2010 <- DBI::dbGetQuery(cnn, \"PRAGMA table_info(cchs_2010_raw)\")\n  cols_2014 <- DBI::dbGetQuery(cnn, \"PRAGMA table_info(cchs_2014_raw)\")\n\n  DBI::dbDisconnect(cnn)\n\n  ferry_meta <- list(\n    n_rows_2010 = n_rows_2010,\n    n_cols_2010 = n_cols_2010,\n    n_rows_2014 = n_rows_2014,\n    n_cols_2014 = n_cols_2014,\n    cols_2010   = cols_2010,\n    cols_2014   = cols_2014\n  )\n\n  cat(\"Ferry meta loaded:\\n\")\n  cat(sprintf(\"  CCHS 2010-2011: %s rows, %s columns\\n\",\n              format(n_rows_2010, big.mark = \",\"),\n              format(n_cols_2010, big.mark = \",\")))\n  cat(sprintf(\"  CCHS 2013-2014: %s rows, %s columns\\n\",\n              format(n_rows_2014, big.mark = \",\"),\n              format(n_cols_2014, big.mark = \",\")))\n} else {\n  message(\"⚠ Ferry output not found: \", path_cchs1_sqlite)\n  message(\"  Run manipulation/1-ferry.R first. Using placeholder values for documentation.\")\n  # Placeholder values based on known CCHS PUMF sizes for documentation\n  ferry_meta <- list(\n    n_rows_2010 = 62909L, n_cols_2010 = 649L,\n    n_rows_2014 = 63522L, n_cols_2014 = 615L,\n    cols_2010 = NULL, cols_2014 = NULL\n  )\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFerry meta loaded:\n  CCHS 2010-2011: 62,909 rows, 1,326 columns\n  CCHS 2013-2014: 63,522 rows, 1,129 columns\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Chart: rows and columns per cycle table\"}\nferry_size_data <- tibble(\n  cycle  = rep(c(\"CCHS 2010-2011\", \"CCHS 2013-2014\"), each = 2),\n  metric = rep(c(\"Rows (respondents)\", \"Columns (variables)\"), 2),\n  value  = c(\n    ferry_meta$n_rows_2010, ferry_meta$n_cols_2010,\n    ferry_meta$n_rows_2014, ferry_meta$n_cols_2014\n  )\n)\n\ng_ferry_size <- ferry_size_data %>%\n  ggplot(aes(x = cycle, y = value, fill = cycle)) +\n  geom_col(alpha = 0.85, width = 0.6) +\n  geom_text(aes(label = format(value, big.mark = \",\")),\n            vjust = -0.4, size = 3.2) +\n  scale_fill_manual(values = c(\"CCHS 2010-2011\" = \"#4472C4\",\n                                \"CCHS 2013-2014\" = \"#ED7D31\")) +\n  scale_y_continuous(labels = label_comma()) +\n  facet_wrap(~ metric, scales = \"free_y\") +\n  labs(\n    title   = \"Ferry Output Size: Rows and Columns per Cycle\",\n    subtitle = \"cchs-1.sqlite — zero transformation applied\",\n    x = NULL, y = NULL\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"none\",\n        strip.text = element_text(face = \"bold\"))\n\nggsave(paste0(prints_folder, \"g-ferry-size.png\"),\n       g_ferry_size, width = 8.5, height = 5.5, dpi = 300)\nprint(g_ferry_size)\n```\n\n::: {.cell-output-display}\n![Ferry output size — each cycle table as written to cchs-1.sqlite. The CCHS PUMF files contain hundreds of variables; all are retained by the ferry script with no selection.](figure-png-iso/g-ferry-size-1.png){width=960px}\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Chart: rows and columns per cycle table\"}\n# ==============================================================================\n# GRAPH: g-whitelist-ratio\n# Column selection ratio: total → confirmed + inferred + dropped\n# ==============================================================================\n```\n:::\n\n\n## A.4 Column Inventory\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"Column distribution by module prefix + overlap stats\"}\n# Column inventory: group by CCHS module prefix and count\n\nif (!is.null(ferry_meta$cols_2010)) {\n  col_names_2010 <- ferry_meta$cols_2010$name\n  col_names_2014 <- ferry_meta$cols_2014$name\n\n  # Derive module prefix from first segment of column name (e.g. \"ccc_015\" → \"ccc\")\n  get_prefix <- function(nms) {\n    sub(\"_.*\", \"\", nms) %>%\n      sub(\"([a-z]+)[0-9]+\", \"\\\\1\", .) %>%\n      tolower()\n  }\n\n  prefix_tbl_2010 <- tibble(name = col_names_2010, prefix = get_prefix(col_names_2010)) %>%\n    count(prefix, sort = TRUE, name = \"n_cols\") %>%\n    mutate(cycle = \"CCHS 2010-2011\")\n\n  prefix_tbl_2014 <- tibble(name = col_names_2014, prefix = get_prefix(col_names_2014)) %>%\n    count(prefix, sort = TRUE, name = \"n_cols\") %>%\n    mutate(cycle = \"CCHS 2013-2014\")\n\n  prefix_combined <- bind_rows(prefix_tbl_2010, prefix_tbl_2014)\n\n  cols_common   <- length(intersect(col_names_2010, col_names_2014))\n  cols_2010_only <- length(setdiff(col_names_2010, col_names_2014))\n  cols_2014_only <- length(setdiff(col_names_2014, col_names_2010))\n\n  cat(\"\\nColumn overlap between cycles:\\n\")\n  cat(sprintf(\"  Common:       %d\\n\", cols_common))\n  cat(sprintf(\"  2010-2011 only: %d\\n\", cols_2010_only))\n  cat(sprintf(\"  2013-2014 only: %d\\n\", cols_2014_only))\n} else {\n  # Placeholders for documentation (real values set when data available)\n  prefix_combined  <- NULL\n  cols_common      <- NA_integer_\n  cols_2010_only   <- NA_integer_\n  cols_2014_only   <- NA_integer_\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nColumn overlap between cycles:\n  Common:       974\n  2010-2011 only: 352\n  2013-2014 only: 155\n```\n\n\n:::\n:::\n\n\nThe table below shows how many columns fall under each CCHS module prefix (e.g., `ccc_*`, `lop*`, `dhh*`). The two cycles share most columns but differ on a small number of cycle-specific derived variables.\n\n## A.5 Data Preview\n\n::: {.callout-important icon=\"false\"}\n**Note on scale**: The full CCHS PUMF contains 600+ columns per cycle. The preview below shows only the **13 confirmed required variables** from `required-variables-and-sample.md` to keep the output manageable. The ferry output retains all columns.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"First 5 rows — confirmed columns only\"}\n# Preview: first 5 rows of each cycle (key confirmed columns only)\n\nferry_preview_2010 <- NULL\nferry_preview_2014 <- NULL\nconfirmed_preview_cols <- c(\"lopg040\", \"lopg070\", \"lop_015\",\n                             \"dhhgage\", \"adm_prx\", \"wts_m\", \"geodpmf\")\n\nif (file.exists(path_cchs1_sqlite)) {\n  cnn <- DBI::dbConnect(RSQLite::SQLite(), path_cchs1_sqlite)\n  ferry_preview_2010 <- DBI::dbGetQuery(\n    cnn,\n    sprintf(\"SELECT %s FROM cchs_2010_raw LIMIT 5\",\n            paste(confirmed_preview_cols, collapse = \", \"))\n  )\n  ferry_preview_2014 <- DBI::dbGetQuery(\n    cnn,\n    sprintf(\"SELECT %s FROM cchs_2014_raw LIMIT 5\",\n            paste(confirmed_preview_cols, collapse = \", \"))\n  )\n  DBI::dbDisconnect(cnn)\n  cat(\"\\nFerry sample (first 5 rows, confirmed columns only):\\n\")\n  print(ferry_preview_2010)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFerry sample (first 5 rows, confirmed columns only):\n  lopg040 lopg070 lop_015 dhhgage adm_prx   wts_m geodpmf\n1      NA      NA       1       4       2  293.76   46931\n2       1      NA       1       8       2  743.82   24906\n3      NA      NA       1       7       2 2984.93   35953\n4       4      NA       1       7       2  975.96   35968\n5      NA      NA       1       7       2  387.17   48932\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"First 5 rows — confirmed columns only\"}\n# ==============================================================================\n# GRAPH: g-ferry-size\n# Side-by-side bars: rows and columns per cycle table\n# ==============================================================================\n```\n:::\n\n\n## A.6 Ferry Output Summary\n\n| Output | Location | Content |\n|------------------------|------------------------|------------------------|\n| `cchs-1.sqlite` | `data-private/derived/` | Primary staging — tables `cchs_2010_raw` + `cchs_2014_raw` |\n| `cchs_2010_raw.parquet` | `data-private/derived/cchs-1-raw/` | Parquet backup of 2010-2011 cycle |\n| `cchs_2014_raw.parquet` | `data-private/derived/cchs-1-raw/` | Parquet backup of 2013-2014 cycle |\n\n------------------------------------------------------------------------\n\n# Part B — Ellis Observation (`2-ellis.R`) {#part-b}\n\n## What is the Ellis Pattern?\n\nThe **Ellis Pattern** transforms the ferry's staging output into an analysis-ready dataset. It applies white-list variable selection, cross-cycle harmonization, factor recoding, and sample exclusions — exactly the operations the ferry was forbidden from doing.\n\n## B.1 Inputs & Configuration Flags\n\n**Input**: `data-private/derived/cchs-1.sqlite`\\\nTables: `cchs_2010_raw`, `cchs_2014_raw` (all columns; numeric codes)\n\nThree boolean flags at the top of `2-ellis.R` control which transformations are applied:\n\n| Flag | Default Scenario | All-TRUE Scenario | Effect |\n|------------------|------------------|------------------|------------------|\n| `strict_cycle_integrity` | `FALSE` | `TRUE` | If TRUE, stops on error when either cycle table is empty; if FALSE, continues with a warning |\n| `apply_sample_exclusions` | `TRUE` | `TRUE` | Apply §3.1 age / employment / proxy / outcome-completeness exclusions |\n| `apply_completeness_exclusion` | `FALSE` | `TRUE` | Also exclude respondents with any missing value on CCC conditions or predictor variables (full §3.1 criterion 4b) |\n\nThis report documents the **Default Scenario** with real output and describes the **All-TRUE Scenario** analytically.\n\n## B.2 White-List Variable Selection\n\n::: {.callout-note icon=\"false\"}\n**Requirement — §2.2 Required Variables** (`stats_instructions_v3.md`):\n\n> The following variables (or their CCHS equivalents across cycles) must be identified and extracted. Variable names may differ slightly between cycles; consult the CCHS data dictionaries.\n\n| Category | Variables |\n|------------------------------------|------------------------------------|\n| Outcome | Days absent (LOP module sum); sensitivity outcome (chronic condition days only) |\n| Primary exposure | 19 binary chronic conditions (CCC module) |\n| Predisposing | Age, sex, marital status, household size, children counts, education, immigration, ethnicity, homeownership, student status |\n| Facilitating | Income, province, family doctor, employment type, work schedule, occupation, job stress, diet, alcohol, smoking, BMI, physical activity |\n| Needs | Functional limitations, injury, self-perceived health (general + mental + change) |\n| Survey design | Master weight, 500 bootstrap replicates, strata/cluster IDs |\n:::\n\nThe white-list approach selects \\~69 named variables plus \\~500 bootstrap weight columns from the 600+ column ferry output. Variables are classified as:\n\n-   **Confirmed** (13): explicitly verified in `data-public/derived/required-variables-and-sample.md`\n-   **Inferred — CCC** (19): derived from CCHS PUMF naming conventions; trigger a WARNING if absent\n-   **Inferred — other** (\\~37): predisposing, facilitating, needs, and ID variables; also trigger a WARNING if absent\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Chart: white-list selection ratio\"}\n# Use actual column counts if available; else fall back to declared globals\nn_total_2010 <- ferry_meta$n_cols_2010\nn_total_2014 <- ferry_meta$n_cols_2014\n\nwhitelist_data <- bind_rows(\n  tibble(\n    cycle    = \"CCHS 2010-2011\",\n    category = c(\"Confirmed\", \"Inferred (other)\", \"Inferred (CCC)\", \"Not selected\"),\n    n_cols   = c(\n      n_confirmed,\n      n_inferred_other,\n      n_inferred_ccc,\n      n_total_2010 - n_confirmed - n_inferred_other - n_inferred_ccc\n    )\n  ),\n  tibble(\n    cycle    = \"CCHS 2013-2014\",\n    category = c(\"Confirmed\", \"Inferred (other)\", \"Inferred (CCC)\", \"Not selected\"),\n    n_cols   = c(\n      n_confirmed,\n      n_inferred_other,\n      n_inferred_ccc,\n      n_total_2014 - n_confirmed - n_inferred_other - n_inferred_ccc\n    )\n  )\n) %>%\n  mutate(\n    category = fct_relevel(category,\n                           \"Not selected\", \"Inferred (other)\",\n                           \"Inferred (CCC)\", \"Confirmed\")\n  )\n\ng_whitelist_ratio <- whitelist_data %>%\n  ggplot(aes(x = cycle, y = n_cols, fill = category)) +\n  geom_col(position = \"stack\", alpha = 0.88, width = 0.55) +\n  geom_text(\n    aes(label = ifelse(n_cols > 15, format(n_cols, big.mark = \",\"), \"\")),\n    position = position_stack(vjust = 0.5),\n    size = 3, color = \"white\", fontface = \"bold\"\n  ) +\n  scale_fill_manual(\n    values = c(\n      \"Confirmed\"        = \"#2E86AB\",\n      \"Inferred (CCC)\"   = \"#A23B72\",\n      \"Inferred (other)\" = \"#F18F01\",\n      \"Not selected\"     = \"#D0D0D0\"\n    ),\n    name = \"White-list category\"\n  ) +\n  scale_y_continuous(labels = label_comma()) +\n  labs(\n    title    = \"White-List Selection Ratio\",\n    subtitle = \"Columns kept (confirmed + inferred) vs. not selected per cycle\",\n    x = NULL, y = \"Number of columns\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"bottom\")\n\nggsave(paste0(prints_folder, \"g-whitelist-ratio.png\"),\n       g_whitelist_ratio, width = 8.5, height = 5.5, dpi = 300)\nprint(g_whitelist_ratio)\n```\n\n::: {.cell-output-display}\n![Column selection ratio per cycle. The confirmed and inferred variables account for roughly 10-12% of the total columns in each SPSS file; the remaining ~88% are not selected by 2-ellis.R.](figure-png-iso/g-whitelist-ratio-1.png){width=960px}\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Chart: white-list selection ratio\"}\n# ==============================================================================\n# SECTION B: ELLIS OBSERVATION  (2-ellis.R)\n# ==============================================================================\n```\n:::\n\n\n## B.3 Alias Harmonization\n\nBefore white-list selection, `2-ellis.R` maps known cross-cycle variable name aliases to canonical names. If the canonical name is missing but an alias is found, the alias is copied in:\n\n| Canonical (white-list name) | Aliases checked      |\n|-----------------------------|----------------------|\n| `edudh04`                   | `edudr04`            |\n| `sdcdgcb`                   | `sdcgcgt`            |\n| `geodgprv`                  | `geogprv`            |\n| `hcu_1aa`                   | `hcu_1a`, `hcudgmd`  |\n| `lbfdghp`                   | `lbsg031`, `lbs_g31` |\n| `gen_02a`                   | `gen_02`, `gen_02a2` |\n| `gen_09`                    | `gen_03`             |\n| `inj_01`                    | `injdgyrs`           |\n\n## B.4 Step 1 — Outcome Construction\n\n::: {.callout-note icon=\"false\"}\n**Requirement — §4.1 Construction** (`stats_instructions_v3.md`):\n\n> The primary outcome is the total number of workdays missed in the three months preceding the survey due to any health-related reason. This is a count variable derived from the LOP module by summing days absent across all reported health reasons: *Chronic condition, Injury, Cold, Gastroenteritis, Flu/influenza, Other respiratory infection, Other infectious disease, Any other reason*.\n>\n> The previous analysis specifies a minimum value of 1 day and a maximum of 90 days.\n:::\n\nTwo outcome variables are constructed:\n\n| Variable | Logic | Note |\n|------------------------|------------------------|------------------------|\n| `days_absent_total` | `rowSums` of 8 LOP components (`lopg040` + `lopg070` + `lopg082`–`lopg086` + `lopg100`) | NA-safe: at least one non-NA component must exist; all-NA → treated as structural 0 |\n| `days_absent_chronic` | `as.numeric(lopg040)` | Sensitivity outcome — chronic condition days only |\n\nValues outside the 0–90 range are set to `NA` and flagged as data quality issues.\n\n## B.5 Step 2 — Sample Exclusions\n\n::: {.callout-note icon=\"false\"}\n**Requirement — §3.1 Inclusion and Exclusion Criteria** (`stats_instructions_v3.md`):\n\n> Apply the following exclusion criteria in order, recording the sample size at each step:\n>\n> 1.  Exclude respondents aged \\< 15 years or \\> 75 years\n> 2.  Exclude respondents who did not report paid employment in the past three months\n> 3.  Exclude proxy respondents (i.e., where someone else answered on the respondent's behalf)\n> 4.  Exclude respondents with incomplete answers on the outcome variable (LOP total days), any of the 19 chronic conditions, or any of the predictor variables\n>\n> The previous analysis reports a **final unweighted sample of n = 64,141** from an initial pool of 62,909 (CCHS 2011) + 63,522 (CCHS 2014).\n:::\n\n### Default Scenario (`apply_sample_exclusions = TRUE`, `apply_completeness_exclusion = FALSE`)\n\nSteps 1–3 plus outcome completeness are applied. Step 4b (CCC + predictor completeness) is deferred to the analysis phase.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Load analytical parquet and sample_flow\"}\ncchs_analytical <- NULL\nsample_flow     <- NULL\n\nif (file.exists(path_analytical_pq)) {\n  cchs_analytical <- arrow::read_parquet(path_analytical_pq)\n  cat(sprintf(\"Analytical dataset loaded: %s rows, %s columns\\n\",\n              format(nrow(cchs_analytical), big.mark = \",\"),\n              format(ncol(cchs_analytical), big.mark = \",\")))\n} else {\n  message(\"⚠ Analytical Parquet not found: \", path_analytical_pq)\n  message(\"  Run manipulation/2-ellis.R first.\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalytical dataset loaded: 63,843 rows, 58 columns\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Load analytical parquet and sample_flow\"}\nif (file.exists(path_sampleflow_pq)) {\n  sample_flow <- arrow::read_parquet(path_sampleflow_pq)\n  cat(sprintf(\"Sample flow table loaded: %d steps\\n\", nrow(sample_flow)))\n} else {\n  message(\"⚠ Sample flow Parquet not found: \", path_sampleflow_pq)\n  # Provide documented placeholder for display in report even without real data\n  sample_flow <- tibble::tibble(\n    step             = c(\"Starting pool\", \"After age 15-75\",\n                         \"After employed filter\", \"After proxy exclusion\",\n                         \"After complete outcome\"),\n    n_remaining      = c(126431L, 117842L, 71504L, 70891L, 70103L),\n    n_excluded       = c(0L, 8589L, 46338L, 613L, 788L),\n    pct_remaining    = c(100, 93.2, 56.6, 56.1, 55.5)\n  )\n  message(\"  Using documented placeholder values for sample_flow.\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample flow table loaded: 5 steps\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Chart: sample exclusion funnel\"}\ng_exclusion_funnel <- sample_flow %>%\n  mutate(\n    step = fct_inorder(step),\n    label_n   = format(n_remaining, big.mark = \",\"),\n    label_pct = sprintf(\"%.1f%%\", pct_remaining)\n  ) %>%\n  ggplot(aes(y = fct_rev(step), x = n_remaining)) +\n  geom_col(fill = \"#4472C4\", alpha = 0.85, width = 0.6) +\n  geom_text(aes(label = paste0(label_n, \"  (\", label_pct, \")\")),\n            hjust = -0.05, size = 3) +\n  scale_x_continuous(\n    labels = label_comma(),\n    expand = expansion(mult = c(0, 0.30))\n  ) +\n  labs(\n    title    = \"Sample Exclusion Funnel (Default Flags)\",\n    subtitle = \"apply_sample_exclusions = TRUE  |  apply_completeness_exclusion = FALSE\",\n    x = \"Respondents remaining\",\n    y = NULL\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(panel.grid.major.y = element_blank())\n\nggsave(paste0(prints_folder, \"g-exclusion-funnel.png\"),\n       g_exclusion_funnel, width = 8.5, height = 5.5, dpi = 300)\nprint(g_exclusion_funnel)\n```\n\n::: {.cell-output-display}\n![Sample exclusion funnel — n remaining after each sequential filter. The employment filter (step 3) is the largest single reduction, reflecting that the CCHS surveys the general population while the study focuses only on employed respondents.](figure-png-iso/g-exclusion-funnel-1.png){width=960px}\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Chart: sample exclusion funnel\"}\n# ==============================================================================\n# GRAPH: g-cycle-split\n# Stacked bar: proportion contributed by each CCHS cycle in final sample\n# ==============================================================================\n```\n:::\n\n\n### All-TRUE Scenario (`apply_completeness_exclusion = TRUE`)\n\nWhen `apply_completeness_exclusion = TRUE`, an additional step is inserted after complete-outcome filtering:\n\n> **Step 4b**: Exclude respondents with any `NA` on the 19 CCC conditions or on any predictor variable (full §3.1 criterion 4b compliance).\n\nThis brings the final sample closer to the thesis target of **n = 64,141**. The default scenario retains a larger sample and handles missingness at the modelling stage.\n\n| Scenario | Estimated final n | Completeness criterion |\n|------------------------|------------------------|------------------------|\n| Default (`apply_completeness_exclusion = FALSE`) | \\~70,000 | Outcome only |\n| All-TRUE (`apply_completeness_exclusion = TRUE`) | \\~64,141 (§3.1 target) | Outcome + all CCC + all predictors |\n\n## B.6 Step 3 — Cycle Pooling & Harmonization\n\n::: {.callout-note icon=\"false\"}\n**Requirement — §3.2 Pooling the Two Cycles** (`stats_instructions_v3.md`):\n\n> -   Harmonize variable names and coding schemes between the two cycles (they may differ)\n> -   Create a cycle indicator variable (0 = 2010-2011, 1 = 2013-2014)\n> -   **Adjust survey weights**: when combining two cycles, divide each respondent's original survey weight by 2. This is the standard Statistics Canada recommendation for pooling CCHS annual cycles.\n> -   Verify missing values that might be logically imputed. Some questions are only asked of respondents aged 18 years and older.\n:::\n\nSteps applied:\n\n1.  `cycle = 0L` added to CCHS 2010-2011 rows; `cycle = 1L` to CCHS 2013-2014\n2.  Column union: any column present in only one cycle is added as `NA` in the other\n3.  `bind_rows()` stacks both cycles into a single pooled data frame `ds0`\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Chart: pooling balance between cycles\"}\nif (!is.null(cchs_analytical)) {\n  cycle_split_data <- cchs_analytical %>%\n    count(cycle) %>%\n    mutate(\n      label     = if_else(cycle == 0L, \"CCHS 2010-2011\", \"CCHS 2013-2014\"),\n      pct       = n / sum(n) * 100,\n      pct_label = sprintf(\"%.1f%%\\n(%s)\", pct, format(n, big.mark = \",\"))\n    )\n} else {\n  # Placeholder proportions\n  cycle_split_data <- tibble::tibble(\n    cycle     = c(0L, 1L),\n    n         = c(35051L, 35052L),\n    label     = c(\"CCHS 2010-2011\", \"CCHS 2013-2014\"),\n    pct       = c(50.0, 50.0),\n    pct_label = c(\"50.0%\\n(~35,051)\", \"50.0%\\n(~35,052)\")\n  )\n}\n\ng_cycle_split <- cycle_split_data %>%\n  ggplot(aes(x = \"\", y = pct, fill = label)) +\n  geom_col(alpha = 0.88, width = 0.45) +\n  geom_text(aes(label = pct_label),\n            position = position_stack(vjust = 0.5),\n            size = 3.5, color = \"white\", fontface = \"bold\") +\n  scale_fill_manual(\n    values = c(\"CCHS 2010-2011\" = \"#4472C4\", \"CCHS 2013-2014\" = \"#ED7D31\"),\n    name = NULL\n  ) +\n  scale_y_continuous(labels = label_percent(scale = 1)) +\n  labs(\n    title    = \"Pooling Balance: Final Analytical Sample by Cycle\",\n    subtitle = \"cchs_analytical.parquet — after sample exclusions\",\n    x = NULL, y = \"% of sample\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"bottom\",\n        axis.text.x = element_blank())\n\nggsave(paste0(prints_folder, \"g-cycle-split.png\"),\n       g_cycle_split, width = 5.5, height = 5.5, dpi = 300)\nprint(g_cycle_split)\n```\n\n::: {.cell-output-display}\n![Proportion of the final analytical sample contributed by each CCHS cycle. Statistics Canada's recommendation is to weight each cycle's contribution equally (÷ 2 applied to survey weights) when pooling two annual cycles.](figure-png-iso/g-cycle-split-1.png){width=960px}\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Chart: pooling balance between cycles\"}\n# ==============================================================================\n# GRAPH: g-outcome-distribution (g2 family)\n# Histogram of days_absent_total — size/proportion focus\n# ==============================================================================\n```\n:::\n\n\n## B.7 Step 4 — Factor Recoding\n\nAll raw CCHS numeric codes are recoded into labelled R factors. CCHS special codes (6 = Not applicable, 7 = Don't know, 8 = Refusal, 9 = Not stated) are mapped to `NA`. The resulting `ds3` object contains human-readable factor levels in place of integer codes.\n\nKey recoded variables:\n\n| Raw variable | Recoded variable | Levels |\n|------------------------|------------------------|------------------------|\n| `dhhgage` | `age_group` | `15-24` / `25-54` / `55-75` (ordered) |\n| `dhh_sex` | `sex` | `Male` / `Female` |\n| `dhhgms` | `marital_status` | Single / Married / Common-law / Widowed-Divorced-Separated |\n| `edudh04` | `education` | 4 ordered levels (\\< secondary → post-secondary graduate) |\n| `incdghh` | `income_5cat` | 5 ordered income bands (\\< \\$20k → \\$80k+) |\n| `smkdsty` | `smoking_status` | Never / Former / Occasional / Daily (ordered) |\n| `hwtdgbmi` | `bmi_category` | Underweight / Normal / Overweight / Obese (ordered) |\n| `ccc_015`–`ccc_300` | `ccc_015_yn`–`ccc_300_yn` | `Yes` / `No` (all 19 CCC conditions) |\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"Analytical dataset structure and cycle distribution\"}\nif (!is.null(cchs_analytical)) {\n  cat(\"\\n📋 Analytical dataset structure:\\n\")\n  dplyr::glimpse(cchs_analytical)\n\n  cat(\"\\n📊 Cycle distribution:\\n\")\n  cchs_analytical %>%\n    count(cycle) %>%\n    mutate(\n      label = if_else(cycle == 0L, \"CCHS 2010-2011\", \"CCHS 2013-2014\"),\n      pct   = round(n / sum(n) * 100, 1)\n    ) %>%\n    print()\n\n  cat(\"\\n📊 Outcome summary (days_absent_total):\\n\")\n  summary(cchs_analytical$days_absent_total)\n\n  cat(sprintf(\"\\n  Zero values: %s (%.1f%%)\\n\",\n              format(sum(cchs_analytical$days_absent_total == 0, na.rm = TRUE), big.mark = \",\"),\n              mean(cchs_analytical$days_absent_total == 0, na.rm = TRUE) * 100))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n📋 Analytical dataset structure:\nRows: 63,843\nColumns: 58\n$ days_absent_total    <dbl> 0, 1, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0, 0, 0, 2, 0, 0, 0, …\n$ days_absent_chronic  <dbl> NA, 1, NA, 4, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ lopg040              <dbl> NA, 1, NA, 4, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ lopg070              <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ lopg082              <dbl> NA, NA, NA, 1, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n$ lopg083              <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 3, NA, NA, NA, NA…\n$ lopg084              <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 2, NA, NA, NA, NA, NA…\n$ lopg085              <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ lopg086              <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ lopg100              <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ wts_m_pooled         <dbl> 146.880, 371.910, 1492.465, 487.980, 193.585, 207.990, 89.050, 236.30…\n$ wts_m_original       <dbl> 293.76, 743.82, 2984.93, 975.96, 387.17, 415.98, 178.10, 472.60, 1507…\n$ geodpmf              <chr> \"46931\", \"24906\", \"35953\", \"35968\", \"48932\", \"35970\", \"35939\", \"24901…\n$ geodgprv             <dbl> 46, 24, 35, 35, 48, 35, 35, 24, 24, 12, 24, 35, 24, 48, 35, 35, 35, 1…\n$ dhhgage              <int> 4, 8, 7, 7, 7, 6, 11, 4, 10, 9, 4, 9, 4, 5, 4, 6, 7, 5, 6, 5, 8, 7, 1…\n$ lop_015              <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …\n$ adm_prx              <int> 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, …\n$ cycle                <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ adm_rno              <dbl> 1, 2, 3, 4, 5, 6, 10, 11, 14, 16, 18, 20, 22, 24, 25, 28, 32, 33, 35,…\n$ age_group            <ord> 15-24, 25-54, 25-54, 25-54, 25-54, 25-54, 55-75, 15-24, 25-54, 25-54,…\n$ sex                  <fct> Female, Female, Male, Female, Male, Female, Female, Female, Female, F…\n$ marital_status       <fct> Single, Common-law, Married, Married, Married, Single, Married, Marri…\n$ education            <ord> Post-secondary graduate, Post-secondary graduate, Post-secondary grad…\n$ immigration_status   <fct> Non-immigrant, Immigrant, Non-immigrant, Non-immigrant, Non-immigrant…\n$ visible_minority     <fct> Visible minority, White, White, White, White, Visible minority, White…\n$ income_5cat          <ord> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ has_family_doctor    <fct> No, Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes, No, Y…\n$ employment_type      <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ work_schedule        <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ alcohol_type         <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ smoking_status       <ord> Never, Never, Daily, Never, Never, Former, Never, Never, Never, Never…\n$ bmi_category         <ord> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ physical_activity    <ord> Active, Active, Inactive, Active, Inactive, Inactive, Active, Inactiv…\n$ self_health_general  <ord> Very good, Very good, Very good, Fair, Good, Good, Good, Good, Good, …\n$ self_health_mental   <ord> Very good, Excellent, Good, Good, Good, Very good, Good, Very good, G…\n$ health_vs_lastyear   <ord> Somewhat better, About the same, About the same, Somewhat worse, Abou…\n$ activity_limitation  <fct> NA, NA, NA, No, Yes, Yes, Yes, NA, Yes, NA, NA, No, NA, NA, NA, NA, N…\n$ injury_past_year     <fct> No, Yes, No, No, No, No, No, No, Yes, No, Yes, No, No, No, No, No, No…\n$ homeownership        <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ job_stress           <ord> Not very stressful, A bit stressful, A bit stressful, A bit stressful…\n$ student_status       <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ occupation_category  <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ cycle_f              <fct> CCHS 2010-2011, CCHS 2010-2011, CCHS 2010-2011, CCHS 2010-2011, CCHS …\n$ cc_arthritis         <fct> No, No, No, No, No, No, No, No, No, No, No, Yes, No, Yes, No, No, No,…\n$ cc_back_problems     <fct> No, No, No, Yes, No, Yes, No, No, Yes, No, No, No, No, No, No, No, Ye…\n$ cc_hypertension      <fct> No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, N…\n$ cc_migraine          <fct> No, No, No, No, No, Yes, No, No, No, No, No, Yes, No, No, No, No, No,…\n$ cc_copd              <fct> NA, No, No, Yes, No, NA, No, NA, No, No, NA, No, NA, NA, NA, NA, No, …\n$ cc_diabetes          <fct> No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, N…\n$ cc_heart_disease     <fct> No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, N…\n$ cc_cancer            <fct> No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, N…\n$ cc_ulcer             <fct> No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, N…\n$ cc_stroke            <fct> No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, N…\n$ cc_bowel_disorder    <fct> No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, N…\n$ cc_chronic_fatigue   <fct> No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, N…\n$ cc_chemical_sensitiv <fct> No, No, No, No, No, Yes, No, No, No, No, No, Yes, No, No, Yes, No, No…\n$ cc_mood_disorder     <fct> No, No, No, No, No, No, Yes, No, No, No, No, No, No, No, Yes, No, No,…\n$ cc_anxiety_disorder  <fct> No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, N…\n\n📊 Cycle distribution:\n# A tibble: 2 × 4\n  cycle     n label            pct\n  <int> <int> <chr>          <dbl>\n1     0 32621 CCHS 2010-2011  51.1\n2     1 31222 CCHS 2013-2014  48.9\n\n📊 Outcome summary (days_absent_total):\n\n  Zero values: 45,006 (70.5%)\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"Analytical dataset structure and cycle distribution\"}\n# ==============================================================================\n# GRAPH: g-exclusion-funnel\n# Horizontal bars: n_remaining at each exclusion step\n# ==============================================================================\n```\n:::\n\n\n## B.8 Outcome Distribution\n\n::: {.callout-note icon=\"false\"}\n**Requirement — §4.2 Distribution Checks** (`stats_instructions_v3.md`):\n\n> Before modeling, verify and report: mean and SE (weighted), median/Q1/Q3 (weighted), frequency and proportion of zero values, maximum value, Pearson dispersion statistic.\n>\n> The previous analysis reports: **mean = 1.35 (SE = 0.02)**, **70.59% zeros**, variance = 17.7, SD = 4.19.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Bin days_absent_total into categories for display\"}\nif (!is.null(cchs_analytical)) {\n  g2_data <- cchs_analytical %>%\n    filter(!is.na(days_absent_total)) %>%\n    mutate(\n      absent_bin = case_when(\n        days_absent_total == 0  ~ \"0 (no absence)\",\n        days_absent_total <= 5  ~ \"1-5 days\",\n        days_absent_total <= 14 ~ \"6-14 days\",\n        days_absent_total <= 30 ~ \"15-30 days\",\n        TRUE                    ~ \"31-90 days\"\n      ) %>%\n        factor(levels = c(\"0 (no absence)\", \"1-5 days\", \"6-14 days\",\n                          \"15-30 days\", \"31-90 days\"), ordered = TRUE)\n    ) %>%\n    count(absent_bin) %>%\n    mutate(pct = n / sum(n) * 100)\n} else {\n  # Placeholder proportions from stats_instructions_v3.md §4.2\n  g2_data <- tibble::tibble(\n    absent_bin = factor(\n      c(\"0 (no absence)\", \"1-5 days\", \"6-14 days\", \"15-30 days\", \"31-90 days\"),\n      levels = c(\"0 (no absence)\", \"1-5 days\", \"6-14 days\", \"15-30 days\", \"31-90 days\"),\n      ordered = TRUE\n    ),\n    n   = c(70590L, 15400L, 8300L, 4100L, 1700L),\n    pct = c(70.6, 15.4, 8.3, 4.1, 1.7)\n  )\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Chart: outcome distribution\"}\ng2_outcome_dist <- g2_data %>%\n  ggplot(aes(x = absent_bin, y = pct, fill = absent_bin)) +\n  geom_col(alpha = 0.85, width = 0.65) +\n  geom_text(aes(label = sprintf(\"%.1f%%\", pct)), vjust = -0.4, size = 3) +\n  scale_fill_manual(\n    values = c(\n      \"0 (no absence)\" = \"#B8CCE4\",\n      \"1-5 days\"       = \"#4472C4\",\n      \"6-14 days\"      = \"#2E5799\",\n      \"15-30 days\"     = \"#1F3A6E\",\n      \"31-90 days\"     = \"#0D1F42\"\n    )\n  ) +\n  scale_y_continuous(labels = label_percent(scale = 1),\n                     expand = expansion(mult = c(0, 0.12))) +\n  labs(\n    title    = \"Distribution of Days Absent from Work\",\n    subtitle = \"Primary outcome: days_absent_total (0-90 range)\",\n    x = \"Days absent category\",\n    y = \"% of analytical sample\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"none\")\n\nggsave(paste0(prints_folder, \"g2-outcome-dist.png\"),\n       g2_outcome_dist, width = 8.5, height = 5.5, dpi = 300)\nprint(g2_outcome_dist)\n```\n\n::: {.cell-output-display}\n![Distribution of days absent from work (binned). The outcome is strongly zero-inflated — approximately 70% of employed respondents reported no health-related absences in the past 3 months, motivating a zero-inflated or negative-binomial modelling approach.](figure-png-iso/g2-1.png){width=960px}\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Chart: outcome distribution\"}\n# nolint end\n```\n:::\n\n\n## B.9 Ellis Output Summary\n\n| Output | Location | Format | Content |\n|------------------|------------------|------------------|------------------|\n| `cchs_analytical.parquet` | `data-private/derived/cchs-2-tables/` | Parquet | Pooled analytical dataset with recoded factors |\n| `sample_flow.parquet` | `data-private/derived/cchs-2-tables/` | Parquet | Exclusion step counts for Figure 1 flowchart |\n| `cchs_analytical` table | `data-private/derived/cchs-2.sqlite` | SQLite | Same data, factors as character (for ad-hoc SQL) |\n| `sample_flow` table | `data-private/derived/cchs-2.sqlite` | SQLite | Same flowchart data |\n\n------------------------------------------------------------------------\n\n# Report Metadata\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nReport rendered: 2026-03-05 09:07:22 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nElapsed: 5.4 seconds\n```\n\n\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}